name: Package N1 Firmware from URL

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package OpenWrt for N1
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMSR: https://github.com/chenleilei1985-del/amlogic-s9xxx-openwrt-1-/releases/download/OpenWrt_immortalwrt_master_save_2026.09/immortalwrt-armsr-armv8-generic-rootfs.tar.gz
          PACKAGE_SOC: s905d
          KERNEL_VERSION_NAME: 6.12.y          # 改成和成功固件接近的 6.12 系列
          KERNEL_AUTO_LATEST: true
          OPENWRT_IP: 192.168.1.1

      - name: Upload OpenWrt Firmware
        uses: actions/upload-artifact@v4
        with:
          name: openwrt-s905d-firmware
          path: ${{ env.PACKAGED_OUTPUTPATH }}/*
