name: Package N1 Firmware

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Package OpenWrt for N1
        uses: ophub/flippy-openwrt-actions@main
        env:
          OPENWRT_ARMSR: openwrt/bin/targets/*/*/*.tar.gz # 指向你编译好的 rootfs 相对路径或下载直链
          PACKAGE_SOC: s905d # 斐讯N1的芯片型号
          KERNEL_VERSION_NAME: 6.12.y # 可根据需要选择内核版本系列
          KERNEL_AUTO_LATEST: true
          OPENWRT_IP: 10.9.8.7
